### PR TITLE
Log refactoring

### LINKED ISSUE #141: Define and implement a flow for sending logs to us in case of an error
A user should be able to send us the logs in case he faces an error.

- [ ] Make the logger write to a file
- [ ] Verify there is a global exception handler that logs exceptions
- [ ] Add to the readme a description of how to send logs (either manual or automatic)
- [ ] Make sure we printing things to the log alongside the UI (scraping events, for example)
- [ ] Make sure we are re-assigning the console.log function, or we linting to not use it and use our custom logger instead.

### PR DESCRIPTION
**Pull request by baruchiro**
Close #141

> A user should be able to send us the logs in case he faces an error.
> 
> * [x]  Make the logger write to a file
> * [x]  Verify there is a global exception handler that logs exceptions
> * [x]  Add to the readme a description of how to send logs (either manual or automatic)
> * [ ]  Make sure we printing things to the log alongside the UI (scraping events, for example)
> * [ ]  Make sure we are re-assigning the console.log function, or we linting to not use it and use our custom logger instead.

### CODE REVIEW

File: src/backend/eventEmitters/compositeEventPublisher.ts [hunk 1]
```diff
@@ -1,11 +0,0 @@
...
-
-export function buildCompositeEventPublisher(eventPublishers: EventPublisher[]): EventPublisher {
-  const compositeEmitter = new BudgetTrackingEventEmitter();
-
-  compositeEmitter.onAny(((eventName, eventData) => {
-    // @ts-ignore
-    eventPublishers.map((eventPublisher) => eventPublisher.emit(eventName, eventData));
-  }));
-  return compositeEmitter;
-}
```
Comment (baruchiro) [inline src/backend/eventEmitters/compositeEventPublisher.ts:11]: This is not a special logic, that should be part of the "eventEmitters" tools. Anyone knows how to write a function like this.

You may remember my conflict with the "EventEmitter", so I removed some codes here, to remove complexity, since all we want from the "backend user" is to give us an object that only implement an interface with `emit`.

File: src/backend/eventEmitters/consoleEmitter.ts [hunk 2]
```diff
@@ -1,11 +0,0 @@
...
-import { BudgetTrackingEventEmitter, EventPublisher } from '@/backend/eventEmitters/EventEmitter';
-
-export function buildConsoleEmitter(): EventPublisher {
-  const consoleEmitter = new BudgetTrackingEventEmitter();
-  consoleEmitter.onAny((eventName, eventData) => {
-    // eslint-disable-next-line no-console
-    console.log(`${eventName}:`, eventData);
-  });
-  return consoleEmitter;
-}
```
Comment (baruchiro) [inline src/backend/eventEmitters/consoleEmitter.ts:11]: As backend (think about the option to implement CLI in the future, for example), you not sure you will print to the console, you leave it to the "backend user" decision.

Comment (baruchiro) [reply src/backend/eventEmitters/consoleEmitter.ts:11]: But see the new `loggerEmitter`, it is very similar.

File: src/backend/eventEmitters/loggerEmitter.ts [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+  info: (...params: any[]) => void
+}
+
+export function buildLoggerEmitter(logger: Logger): EventPublisher {
+  const loggerEmitter = new BudgetTrackingEventEmitter();
+  loggerEmitter.onAny((eventName, eventData) => {
+    logger.info(`${eventName}:`, eventData);
+  });
+  return loggerEmitter;
+}
```
Comment (baruchiro) [inline src/backend/eventEmitters/loggerEmitter.ts:13]: This is not a very smart method, but it is here for a reason.

Here, in the `eventEmitters` folder, in the context of the `eventEmitters`, we know the event types, so we can parse them to string (with special care for each event), and direct them to the right level.

So, continuously, we can use this method to

1. Print specific message depends on the Event.
2. Print to the console or to the file, by level (because the `logger` argument supports both `console.[level]` and `logger.[level]`

File: src/logging/logger.ts [hunk 4]
```diff
@@ -1,29 +1,24 @@
-import { App } from 'electron';
-import logger from 'electron-log';
+import { App } from '@/app-globals';
+import logger, { LogFunctions, LogLevel } from 'electron-log'; // eslint-disable-line no-restricted-imports
```
Comment (baruchiro) [inline src/logging/logger.ts:2]: If you will try to `import logger from 'electron-log'`, you will get an *ESLint* error, because we want you to use our custom-defined logger.
But here we have to import the logger from `electron-log` to configure it.

File: src/logging/logger.ts [hunk 5]
```diff
@@ -1,29 +1,24 @@
...
-  const onError = (error: Error) => {
-    logger.error(error.message ? error.message : error);
-    if (error.stack) logger.debug(error.stack);
-  };
-  logger.catchErrors({ onError });
+const onError = (error: Error) => {
+  logger.error(error.message || error);
+  if (error.stack) logger.debug(error.stack);
+};
+logger.catchErrors({ onError });
```
Comment (baruchiro) [inline src/logging/logger.ts:16]: Note, this catching only the `UnhandledRejection`.

At least for the Vue part, we need to open a new issue to catch exceptions during the render process (I even can't say what exactly happened during such case. For in React, for example, the component tree will crash- if you're not using error boundary)

Comment (baruchiro) [reply src/logging/logger.ts:16]: #198

File: README.md [hunk 6]
```diff
@@ -31,6 +31,13 @@ The first time you run the app, you will need to set up the accounts you want to
 Now you can set up the exporters - where the data will be sent to. The CSV exporter is enabled by default.
 If you want to export to YNAB, see instructions at the end of the README.
 
+### Report a problem
+
+We are still in beta, and you may find errors.
+Please use the **REPORT A PROBLEM** button in the app to report to us.
+
+Use this button to find the **logs folder** as well.
+
```
Comment (baruchiro) [inline README.md:40]: Please review

File: src/ui/components/app/ReportProblemDialog.vue [hunk 7]
```diff
@@ -60,6 +60,8 @@
             </v-row>
           </v-container>
           <small>*indicates required field</small>
+          <br>
+          <small>You can find the logs here: {{ logsDir }}</small>
```
Comment (baruchiro) [inline src/ui/components/app/ReportProblemDialog.vue:64]: image

**Comment by baruchiro** [comment]
@brafdlog Ready for review.

I skipping the two checkboxes. This PR is already big.
